config/routes.rb
Rails.application.routes.draw do
  resources :plants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "plants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: %i[ show edit update destroy ]

  # GET /plants or /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1 or /plants/1.json
  def show

  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants or /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully created." }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1 or /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully updated." }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1 or /plants/1.json
  def destroy
    @plant.destroy

    respond_to do |format|
      format.html { redirect_to plants_url, notice: "Plant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.require(:plant).permit(
        :alarm_enable,
        :alarm_interval,
        :auto_water,
        :dry_point, 
        :name,
        :sync_key,
        :pump_speed,
        :pump_time,
        :warn_level,
        :water_level,
        :watering_delay,
        :wet_point
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantWebApp3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body style="padding-top: 60px;">
    <div class="container-fluid">
      <nav class="navbar fixed-top">
        <div class="container px-3">
          <%= link_to "Home", plants_path, class: "navbar-brand" %>
        </div>
      </nav>
      <div class="container">
        <div class="row">
          <div class="col">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/plants/_form.html.erb
<%= form_with model: @plant do |form| %>
  <div class="row justify-content-center mt-3">
    <div class="col-4">
      <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, placeholder: "Bob the plant", class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :sync_key, class: "form-label" %>
        <%= form.text_field :sync_key, class: "form-control" %>
      </div>
      <div class="mb-3 col-4">
        <%= form.label :alarm_interval, class: "form-label" %>
        <%= form.text_field :alarm_interval, value: "2", class: "form-control" %>
      </div>
      <div class="mb-3 col-4">
        <%= form.label :dry_point, class: "form-label" %>
        <%= form.text_field :dry_point, value: "27", class: "form-control" %>
      </div>
      <div class="mb-3 col-4">
        <%= form.label :wet_point, class: "form-label" %>
        <%= form.text_field :wet_point, value: "3", class: "form-control" %>
      </div>
      <div class="mb-3 col-4">
        <%= form.label :pump_speed, class: "form-label" %>
        <%= form.text_field :pump_speed, value: "0.5", class: "form-control" %>
      </div>
      <div class="mb-3 col-4">
        <%= form.label :pump_time, class: "form-label" %>
        <%= form.text_field :pump_time, value: "0.5", class: "form-control" %>
      </div>
      <div class="mb-3 col-4">
        <%= form.label :warn_level, class: "form-label" %>
        <%= form.text_field :warn_level, value: "0.2", class: "form-control" %>
      </div>
      <div class="mb-3 col-4">
        <%= form.label :water_level, class: "form-label" %>
        <%= form.text_field :water_level, value: "", class: "form-control" %>
      </div>
      <div class="mb-3 col-4">
        <%= form.label :watering_delay, class: "form-label" %>
        <%= form.text_field :watering_delay, value: "60", class: "form-control" %>
      </div>

      <div class="form-check">
        <%= form.label :alarm_enable, class: "form-check-label" %>
        <%= form.check_box :alarm_enable, checked: 'checked', class: "form-check-input" %>
      </div>

      <div class="form-check">
        <%= form.label :auto_water, class: "form-check-label" %>
        <%= form.check_box :auto_water, checked: '', class: "form-check-input" %>
      </div>

      <div class="my-3">
        <%= form.submit "Create plant", :class => "btn btn-primary" %>
      </div>

      <div>
        <% @plant.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

    </div>
  </div>
<% end %>

app/views/plants/_plant.html.erb
<div id="<%= dom_id plant %>">
  <%= plant.name %>
</div>

app/views/plants/edit.html.erb
<h1>Editing plant</h1>

<%= render "form", plant: @plant %>

<br>

<div>
  <%= link_to "Show this plant", @plant %> |
  <%= link_to "Back to plants", plants_path %>
</div>

app/views/plants/index.html.erb
<div class="row mb-3">
  <div class="col">
    <h2>Your plants</h2>
  </div>
  <div class="col text-end">
    <%= link_to 'Add plant', new_plant_path, class: "btn btn-primary" %>
  </div>
</div>

<div class="row">
  <div class="col">
    <div class="row row-cols-1 row-cols-md-3 g-4">

      <% @plants.each do |plant| %>
        <div class="col">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= link_to (plant.name.present? ? plant.name : 'Plant'), plant %></h5>
              <span class="badge bg-secondary"><%= plant.sync_key %></span>
            </div>
          </div>
        </div>
      <% end %>

    </div>

    <% if @plants.empty? %>
      <div class="card border-0 pt-5 pb-5">
        <div class="card-body text-center">
          <h3>Oh no! There are no plants!</h3>
          <%= link_to "Add a plant", new_plant_path, :class => "btn btn-primary" %>
        </div>
      </div>

    <% end %>

  </div>
</div>

app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render "form", plant: @plant %>

<br>

<div>
  <%= link_to "Back to plants", plants_path %>
</div>

app/views/plants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @plant %>

<div>
  <%= link_to "Edit this plant", edit_plant_path(@plant) %> |
  <%= link_to "Back to plants", plants_path %>

  <%= button_to "Destroy this plant", @plant, method: :delete %>
</div>